// Fallback data for when the API is unavailable

export const fallbackMovies = [
  {
    id: "1",
    title: "Inception",
    year: "2010",
    poster: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    type: "movie",
    description:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: inception, the implantation of another person's idea into a target's subconscious.",
    rating: 8.8,
    duration: "148 min",
    genres: ["Action", "Science Fiction", "Adventure"],
    streamingUrl: "https://example.com/stream/inception",
  },
  {
    id: "2",
    title: "The Dark Knight",
    year: "2008",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    type: "movie",
    description:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    rating: 9.0,
    duration: "152 min",
    genres: ["Action", "Crime", "Drama", "Thriller"],
    streamingUrl: "https://example.com/stream/the-dark-knight",
  },
  {
    id: "3",
    title: "Interstellar",
    year: "2014",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    type: "movie",
    description:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    rating: 8.6,
    duration: "169 min",
    genres: ["Adventure", "Drama", "Science Fiction"],
    streamingUrl: "https://example.com/stream/interstellar",
  },
  {
    id: "4",
    title: "The Matrix",
    year: "1999",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    type: "movie",
    description:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    rating: 8.7,
    duration: "136 min",
    genres: ["Action", "Science Fiction"],
    streamingUrl: "https://example.com/stream/the-matrix",
  },
  {
    id: "5",
    title: "Pulp Fiction",
    year: "1994",
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    type: "movie",
    description:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    rating: 8.9,
    duration: "154 min",
    genres: ["Thriller", "Crime"],
    streamingUrl: "https://example.com/stream/pulp-fiction",
  },
  {
    id: "6",
    title: "The Shawshank Redemption",
    year: "1994",
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    type: "movie",
    description:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    rating: 8.7,
    duration: "142 min",
    genres: ["Drama", "Crime"],
    streamingUrl: "https://example.com/stream/the-shawshank-redemption",
  },
  {
    id: "7",
    title: "Avengers: Endgame",
    year: "2019",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    type: "movie",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
    rating: 8.4,
    duration: "181 min",
    genres: ["Adventure", "Science Fiction", "Action"],
    streamingUrl: "https://example.com/stream/avengers-endgame",
  },
  {
    id: "8",
    title: "Parasite",
    year: "2019",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    type: "movie",
    description:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    rating: 8.5,
    duration: "132 min",
    genres: ["Comedy", "Thriller", "Drama"],
    streamingUrl: "https://example.com/stream/parasite",
  },
  {
    id: "9",
    title: "Joker",
    year: "2019",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    type: "movie",
    description:
      "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    rating: 8.2,
    duration: "122 min",
    genres: ["Crime", "Thriller", "Drama"],
    streamingUrl: "https://example.com/stream/joker",
  },
  {
    id: "10",
    title: "Dune",
    year: "2021",
    poster: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    type: "movie",
    description:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    rating: 7.9,
    duration: "155 min",
    genres: ["Science Fiction", "Adventure"],
    streamingUrl: "https://example.com/stream/dune",
  },
]

export const fallbackTVShows = [
  {
    id: "101",
    title: "Breaking Bad",
    year: "2008",
    poster: "https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    type: "tv",
    description:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    rating: 8.8,
    duration: "45 min",
    genres: ["Drama", "Crime"],
    streamingUrl: "https://example.com/stream/breaking-bad",
  },
  {
    id: "102",
    title: "Game of Thrones",
    year: "2011",
    poster: "https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
    type: "tv",
    description:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    rating: 8.4,
    duration: "60 min",
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    streamingUrl: "https://example.com/stream/game-of-thrones",
  },
  {
    id: "103",
    title: "Stranger Things",
    year: "2016",
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    type: "tv",
    description:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    rating: 8.6,
    duration: "50 min",
    genres: ["Drama", "Sci-Fi & Fantasy", "Mystery"],
    streamingUrl: "https://example.com/stream/stranger-things",
  },
  {
    id: "104",
    title: "The Mandalorian",
    year: "2019",
    poster: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/o7qi2v4uWQ8bZ1tW3KI0Ztn2epk.jpg",
    type: "tv",
    description:
      "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
    rating: 8.5,
    duration: "35 min",
    genres: ["Sci-Fi & Fantasy", "Action & Adventure", "Western", "Drama"],
    streamingUrl: "https://example.com/stream/the-mandalorian",
  },
  {
    id: "105",
    title: "The Office",
    year: "2005",
    poster: "https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/vNpuAxGTl9HsUbHqam3E9CzqCvX.jpg",
    type: "tv",
    description:
      "The everyday lives of office employees in the Scranton, Pennsylvania branch of the fictional Dunder Mifflin Paper Company.",
    rating: 8.5,
    duration: "22 min",
    genres: ["Comedy"],
    streamingUrl: "https://example.com/stream/the-office",
  },
  {
    id: "106",
    title: "Friends",
    year: "1994",
    poster: "https://image.tmdb.org/t/p/w500/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/l0qVZIpXtIo7km9u5Yqh0nKPOr5.jpg",
    type: "tv",
    description:
      "The misadventures of a group of friends as they navigate the pitfalls of work, life and love in Manhattan.",
    rating: 8.4,
    duration: "25 min",
    genres: ["Comedy", "Drama"],
    streamingUrl: "https://example.com/stream/friends",
  },
  {
    id: "107",
    title: "The Witcher",
    year: "2019",
    poster: "https://image.tmdb.org/t/p/w500/7vjaCdMw15FEbXyLQTVa04URsPm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    type: "tv",
    description:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    rating: 8.2,
    duration: "60 min",
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    streamingUrl: "https://example.com/stream/the-witcher",
  },
  {
    id: "108",
    title: "The Crown",
    year: "2016",
    poster: "https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hQ6iJY0L3aBG9QK1pTPMz0iVDJZ.jpg",
    type: "tv",
    description:
      "The gripping, decades-spanning inside story of Her Majesty Queen Elizabeth II and the Prime Ministers who shaped Britain's post-war destiny.",
    rating: 8.3,
    duration: "52 min",
    genres: ["Drama"],
    streamingUrl: "https://example.com/stream/the-crown",
  },
  {
    id: "109",
    title: "Westworld",
    year: "2016",
    poster: "https://image.tmdb.org/t/p/w500/y55oBgf6bVMI7sFNXwJDrSIxPQt.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/yGNnjoIGOdQy3douq60tULY8teK.jpg",
    type: "tv",
    description:
      "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
    rating: 8.1,
    duration: "60 min",
    genres: ["Western", "Science Fiction"],
    streamingUrl: "https://example.com/stream/westworld",
  },
  {
    id: "110",
    title: "Black Mirror",
    year: "2011",
    poster: "https://image.tmdb.org/t/p/w500/7PRddO7z7mcPi21nJRXDlGbVIdv.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/8GPSeTn6CEqLWX9C8WjhSvnk1kk.jpg",
    type: "tv",
    description:
      "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world.",
    rating: 8.3,
    duration: "60 min",
    genres: ["Sci-Fi & Fantasy", "Drama"],
    streamingUrl: "https://example.com/stream/black-mirror",
  },
]

export const fallbackTrending = [...fallbackMovies.slice(0, 5), ...fallbackTVShows.slice(0, 5)]
